version: '3.6'

services:
  courier:
    # image: auth-app
    build: ./
    ports:
      - 8005:8000
    # depends_on:
    #   - db
    # environment:
    #   - DB_PASSWORD=fuaddauf

networks:
  default:
    name: client_default
  # db:
  #   restart: always
  #   image: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=fuaddauf
  #   ports:
  #     - 5437:5432
  
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8088:8080

# volumes: 
#   postgres_data: